# Fund Deonte Watts's open-source work
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [DeontewattsV1]
ko_fi: deontewatts
buy_me_a_coffee: deontewatts
custom:
  - "https://github.com/sponsors/DeontewattsV1"
